### ISSUE TITLE
Response is Always "No Results Found"

### ISSUE THREAD

**Issue by drdannysands** [vitorgalvao/critic-ratings-workflow#1]
### Workflow version

2023.1

### Alfred version

5.12 [2145]

### macOS version

13.4 (22F66)

### Debugger output

```alfred_debugger
[18:51:22.141] Logging Started...
[18:51:39.217] Critic Ratings[Script Filter] Queuing argument 'hijack'
[18:51:39.808] Critic Ratings[Script Filter] Script with argv 'hijack' finished
[18:51:39.813] Critic Ratings[Script Filter] {"items":[{"title":"No results found for “hijack”"}]}
```

### More details

Hi again @vitorgalvao. Whatever I type as an argument results in "No result found."

![image](https://github.com/vitorgalvao/critic-ratings-workflow/assets/41439108/6b92b1fd-8b11-4f2c-a50f-ef1e916481a9)

I removed and reinstalled workflow and tried restarted Alfred.

Thanks.

Danny

**Comment by vitorgalvao** [comment]
Please try [this version](https://github.com/vitorgalvao/critic-ratings-workflow/files/12732789/Critic.Ratings.alfredworkflow.zip) and let me know if it keeps working.

**Comment by drdannysands** [comment]
It works perfectly. Thank you very much.

- Danny

**Comment by vitorgalvao** [comment]
Thank you for testing. Released in the Gallery.
